name: Auto Update version.json

on:
  push:
    branches: [main]
    paths-ignore:
      - 'version.json'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run version generator
        run: python Update_version.py

      - name: Commit updated version.json
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "AutoUpdater"
          git config user.email "autoupdate@example.com"
          git add version.json
          git commit -m "Auto-update version.json" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
